return {
	kind = {
	  Text = "",
	  Method = "m",
	  Function = "",
	  Constructor = "",
	  Field = "",
	  Variable = "",
	  Class = "",
	  Interface = "",
	  Module = "",
	  Property = "",
	  Unit = "",
	  Value = "",
	  Enum = "",
	  Keyword = "",
	  Snippet = "",
	  Color = "",
	  File = "",
	  Reference = "",
	  Folder = "",
	  EnumMember = "",
	  Constant = "",
	  Struct = "",
	  Event = "",
	  Operator = "",
	  TypeParameter = "",
    Treesitter = "",
	},
	diagnostics = {
	  Error = "",
	  Warning = "",
	  Hint = "",
	  Information = "",
	},
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    FileDeleted = "",
    FileIgnored = "◌",
    FileRenamed = "",
    FileStaged = "S",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "U",
    Diff = "",
    Repo = "",
    Octoface = "",
    Branch = "",
  },
}
